#!/usr/bin/env python3
"""Generate StemTeX profile warmup.tex from a profile preamble.

The generator deliberately covers declared profile capabilities instead of
enumerating TeX Live fonts or guessing real user documents.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def has_package(preamble: str, name: str) -> bool:
    pattern = re.compile(r"\\usepackage(?:\[[^\]]*\])?\{([^}]*)\}")
    for match in pattern.finditer(preamble):
        packages = [part.strip() for part in match.group(1).split(",")]
        if name in packages:
            return True
    return False


def generate_warmup(preamble: str) -> str:
    has_cjk = has_package(preamble, "xeCJK") or "\\setCJK" in preamble
    has_unicode_math = has_package(preamble, "unicode-math") or "\\setmathfont" in preamble
    has_mhchem = has_package(preamble, "mhchem")
    has_physics = has_package(preamble, "physics")
    has_xcolor = has_package(preamble, "xcolor")
    has_cancel = has_package(preamble, "cancel")

    lines: list[str] = [
        "% Generated by scripts/generate-profile-warmup.py.",
        "% Edit the generator rather than hand-tuning this matrix.",
        "\\input{preamble.tex}",
        "",
        "\\begin{document}",
        "\\begin{preview}",
        "",
        "Text font matrix:",
        "\\rmfamily Roman normal 0123456789 ABC xyz, \\textbf{bold ABC xyz}, \\textit{italic ABC xyz},",
        "\\textbf{\\textit{bold italic ABC xyz}}, \\textsf{Sans normal ABC xyz},",
        "\\textsf{\\textbf{Sans bold ABC xyz}}, \\textsf{\\textit{Sans italic ABC xyz}},",
        "\\texttt{Mono normal ABC xyz 0123456789 +-*/= () [] \\{\\}}.",
        "",
    ]

    if has_cjk:
        lines.extend(
            [
                "CJK font matrix:",
                "中文缓存预热，标点测试：，。！？；：“”《》",
                "{\\bfseries 中文粗体预热：数学、化学、物理、单位。}",
                "{\\sffamily 中文黑体预热：向量、矩阵、反应式。}",
                "{\\ttfamily 中文等宽预热：ABC xyz 0123456789。}",
                "",
            ]
        )

    if has_unicode_math:
        lines.extend(
            [
                "Unicode math alphabet matrix:",
                "\\[",
                "  \\mathrm{ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz}",
                "  \\quad \\mathbf{ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz}",
                "  \\quad \\mathit{ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz}",
                "\\]",
                "\\[",
                "  \\mathsf{ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz}",
                "  \\quad \\mathtt{ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz}",
                "\\]",
                "\\[",
                "  \\mathcal{ABCDEFGHIJKLMNOPQRSTUVWXYZ}",
                "  \\quad \\mathbb{ABCDEFGHIJKLMNOPQRSTUVWXYZ}",
                "  \\quad \\mathfrak{ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz}",
                "\\]",
                "\\[",
                "  \\symrm{ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz}",
                "  \\quad \\symbf{ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz}",
                "  \\quad \\symit{ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz}",
                "  \\quad \\symbfit{ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz}",
                "\\]",
                "\\[",
                "  \\symcal{ABCDEFGHIJKLMNOPQRSTUVWXYZ}",
                "  \\quad \\symbfcal{ABCDEFGHIJKLMNOPQRSTUVWXYZ}",
                "  \\quad \\symbb{ABCDEFGHIJKLMNOPQRSTUVWXYZ}",
                "  \\quad \\symfrak{ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz}",
                "\\]",
                "\\[",
                "  \\alpha\\beta\\gamma\\delta\\epsilon\\theta\\lambda\\mu\\pi\\rho\\sigma\\phi\\omega",
                "  \\quad \\Gamma\\Delta\\Theta\\Lambda\\Pi\\Sigma\\Phi\\Omega",
                "  \\quad \\symbf{\\alpha\\beta\\gamma\\Delta\\nabla}",
                "\\]",
                "",
                "Math style and script matrix:",
                "\\[",
                "  E=mc^2 \\quad \\int_0^1 x^2\\,dx = \\frac{1}{3} \\quad",
                "  \\sum_{n=1}^{\\infty}\\frac{1}{n^2}=\\frac{\\pi^2}{6} \\quad",
                "  \\sqrt{x^2+y^2}",
                "\\]",
                "\\[",
                "  x_{i_j}^{k_\\ell} + \\frac{\\frac{a}{b}}{\\sqrt{c_d}} +",
                "  \\left(\\frac{\\partial^2 f}{\\partial x_i\\partial x_j}\\right)_{i,j=1}^{n}",
                "\\]",
                "\\[",
                "  A = \\begin{pmatrix} 1 & 2 \\\\ 3 & 4 \\end{pmatrix}",
                "  \\qquad",
                "  f(x)=\\begin{cases} x^2, & x \\ge 0,\\\\ -x, & x < 0. \\end{cases}",
                "\\]",
                "\\[",
                "  e^{\\mathcal{L}\\Delta t}",
                "  \\approx e^{\\mathcal{L}^{\\mathbf{Middle}}\\Delta t}",
                "  = e^{\\mathcal{L}_{p}\\Delta t/2}",
                "    e^{\\mathcal{L}_{x}\\Delta t/2}",
                "    e^{\\mathcal{L}_{T}\\Delta t}",
                "    e^{\\mathcal{L}_{x}\\Delta t/2}",
                "    e^{\\mathcal{L}_{p}\\Delta t/2}",
                "\\]",
                "",
            ]
        )

    if has_physics:
        lines.extend(
            [
                "Physics package triggers:",
                "\\[",
                "  \\ip{\\psi}{\\phi}\\quad \\dv{x}\\sin x=\\cos x\\quad",
                "  \\pdv{f}{x}\\quad \\vb{v}\\cdot\\vu{n}\\quad \\nabla f",
                "\\]",
                "",
            ]
        )

    if has_mhchem:
        lines.extend(
            [
                "Chemistry package triggers:",
                "\\ce{H2O}, \\ce{CO2}, \\ce{Na+}, \\ce{SO4^2-}, \\ce{A -> B},",
                "\\ce{2H2 + O2 -> 2H2O}.",
                "\\[",
                "  \\ce{CH4 + 2O2 -> CO2 + 2H2O}",
                "\\]",
                "",
            ]
        )

    if has_xcolor:
        lines.extend(
            [
                "Color package triggers:",
                "{\\color{blue}blue text} {\\color{red}red text} {\\color{green!50!black}green text}",
                "{\\color{blue}$E=mc^2$} {\\color{red}$\\mathcal{F}_{x}$}",
                "",
            ]
        )

    if has_cancel:
        lines.extend(
            [
                "Cancel package triggers:",
                "\\[",
                "  \\cancel{x+y}\\quad \\bcancel{a-b}\\quad \\xcancel{z}\\quad \\cancelto{0}{r-r}",
                "\\]",
                "",
            ]
        )

    lines.extend(["\\end{preview}", "\\end{document}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("profile", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    profile = args.profile
    preamble_path = profile / "preamble.tex"
    warmup_path = profile / "warmup.tex"
    preamble = preamble_path.read_text(encoding="utf-8")
    generated = generate_warmup(preamble)

    if args.check:
        current = warmup_path.read_text(encoding="utf-8") if warmup_path.exists() else ""
        return 0 if current == generated else 1

    warmup_path.write_text(generated, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
