#!/usr/bin/env python3
"""Generate a minimal StemTeX profile readiness warmup.tex.

Correctness comes from merging live XDV font definitions in the renderer. The
warmup only verifies that the profile preamble and declared package/font basics
can initialize.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def has_package(preamble: str, name: str) -> bool:
    pattern = re.compile(r"\\usepackage(?:\[[^\]]*\])?\{([^}]*)\}")
    for match in pattern.finditer(preamble):
        packages = [part.strip() for part in match.group(1).split(",")]
        if name in packages:
            return True
    return False


def generate_warmup(preamble: str) -> str:
    has_cjk = has_package(preamble, "xeCJK") or "\\setCJK" in preamble
    has_unicode_math = (
        has_package(preamble, "unicode-math")
        or has_package(preamble, "lete-sans-math")
        or "\\setmathfont" in preamble
    )
    has_mhchem = has_package(preamble, "mhchem")
    lines: list[str] = [
        "% Generated by scripts/generate-profile-warmup.py.",
        "% This is a readiness probe, not a font coverage corpus.",
        "\\input{preamble.tex}",
        "",
        "\\begin{document}",
        "\\begin{preview}",
        "",
        "StemTeX warmup: ABC xyz 0123456789.",
        "\\textbf{bold} \\textit{italic} \\textsf{sans} \\texttt{mono}.",
        "",
    ]

    if has_cjk:
        lines.extend(
            [
                "中文预热：数学、化学、物理；\\textbf{中文粗体}；\\textit{中文斜体}。",
                "",
            ]
        )

    if has_unicode_math:
        lines.extend(
            [
                "\\[",
                "  E=mc^2 \\quad \\alpha+\\beta=\\gamma \\quad \\mathcal{L}_{p} \\quad \\mathbf{x}",
                "\\]",
                "",
            ]
        )

    if has_mhchem:
        lines.extend(
            [
                "\\ce{H2O} \\ce{2H2 + O2 -> 2H2O}.",
                "",
            ]
        )

    lines.extend(["\\end{preview}", "\\end{document}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("profile", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    profile = args.profile
    preamble_path = profile / "preamble.tex"
    warmup_path = profile / "warmup.tex"
    preamble = preamble_path.read_text(encoding="utf-8")
    generated = generate_warmup(preamble)

    if args.check:
        current = warmup_path.read_text(encoding="utf-8") if warmup_path.exists() else ""
        return 0 if current == generated else 1

    warmup_path.write_text(generated, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
